changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Breaking Changes 🛠
      labels:
        - Semver-Major
        - kind/breaking-change
    - title: Exciting New Features 🎉
      labels:
        - Semver-Minor
        - kind/enhancement
    - title: Bug Fix 🐛
        - Semver-Patch
        - kind/bug
    - title: Other Changes
      labels:
        - "*"
